[project]
name = "fincalc"
version = "0.1.1"
description = "A simple example for a Python package in Finance"
authors = [
    { name = "Peter Gruber", email = "peter.gruber@usi.ch" },
    { name = "Mattia Biancaterra", email = "mattia.biancaterra@example.com" } # Replace with the correct email
]
keywords = ["interest", "finance", "present value"]
license = "MIT" # Specify your license here
readme = "README.md" # Assumes you have a README.md file in your project root
repository = "https://github.com/peterhgruber/fincalc"

[project.urls]
homepage = "https://github.com/peterhgruber/fincalc"

[project.dependencies]
requires = [
    "numpy",
    "scipy",
    "pandas"
]
